// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AllocationModule
{
    public partial class ProcessAllocationService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(GetUnAllocationFileCommand cmd)
        {

            GetUnAllocationFilePostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetUnAllocationFilePostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetUnAllocationFilePostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetUnAllocationFilePostBusSequence, GetUnAllocationFilePostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
