// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CompanyUsersModule.AddCompanyUserCompanyUsersPlugins;

namespace ENTiger.ENCollect.CompanyUsersModule
{
    public class AddCompanyUserSequence : FlexiBusinessRuleSequenceBase<AddCompanyUserDataPacket>
    {
        public AddCompanyUserSequence()
        {
            
            this.Add<CheckDuplicateDomainId>(); this.Add<CheckDuplicateEmail>(); this.Add<CheckDuplicateMobile>(); this.Add<CheckWalletLimit>();
        }
    }
}
