// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CompanyUsersModule.EnableCompanyUsersCompanyUsersPlugins;

namespace ENTiger.ENCollect.CompanyUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class EnableCompanyUsersSequence : FlexiBusinessRuleSequenceBase<EnableCompanyUsersDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public EnableCompanyUsersSequence()
        {
            
            this.Add<ValidateUsers>(); 
        }
    }
}
