// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.PayInSlipsModule.GetPayInSlipImagePayInSlipsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckFileAccess : FlexiBusinessRuleBase, IFlexiBusinessRule<GetPayInSlipImageDataPacket>
    {
        public override string Id { get; set; } = "3a1384129ac3e19801ef233e92042b8f";
        public override string FriendlyName { get; set; } = "CheckFileAccess";

        protected readonly ILogger<CheckFileAccess> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected FlexAppContextBridge? _flexAppContext;

        public CheckFileAccess(ILogger<CheckFileAccess> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(GetPayInSlipImageDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);
            _flexAppContext = packet.Dto.GetAppContext();  //do not remove this line

            string userId = _flexAppContext.UserId;

            List<string> filesList = new List<string>();

            var user = await _repoFactory.GetRepo().Find<ApplicationUser>(userId).FirstOrDefaultAsync();
            if (user.GetType().Name.Contains("AgencyUser", StringComparison.OrdinalIgnoreCase))
            {
                var agencyUser = await _repoFactory.GetRepo().Find<AgencyUser>(userId).FirstOrDefaultAsync();

                var collections = await _repoFactory.GetRepo().FindAll<PayInSlip>()
                                                .Where(x => x.CreatedBy == agencyUser.Id)
                                                .ToListAsync();
                if (collections != null && collections.Count() > 0)
                {
                    filesList.AddRange(collections.Select(x => x.PayInSlipImageName).ToList());
                }

                if (filesList.Where(x => x != null && x.Contains(packet.Dto.FileName)).Count() == 0)
                {
                    _logger.LogError("CheckReceiptAccess : Access Denied");
                    packet.AddError("Error", "Access Denied");
                }
            }
        }
    }
}
