// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;
using ENTiger.ENCollect.DomainModels;

namespace ENTiger.ENCollect.PayInSlipsModule.GetPayInSlipImagePayInSlipsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateFile : FlexiBusinessRuleBase, IFlexiBusinessRule<GetPayInSlipImageDataPacket>
    {
        public override string Id { get; set; } = "3a13841292bd0d600d4494c69e1a345e";
        public override string FriendlyName { get; set; } = "ValidateFile";

        protected readonly ILogger<ValidateFile> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileValidationUtility _fileValidationUtility;

        public ValidateFile(ILogger<ValidateFile> logger, IRepoFactory repoFactory, IFileValidationUtility fileValidationUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileValidationUtility = fileValidationUtility;
        }

        public virtual async Task Validate(GetPayInSlipImageDataPacket packet)
        {
            if (!_fileValidationUtility.ValidateFileName(packet.Dto.FileName, out string errorMessage))
            {
                packet.AddError("Error", errorMessage);
            }
            if (!_fileValidationUtility.ValidateDownloadFile(packet.Dto.FileName, out string message))
            {
                packet.AddError("Error", message);
            }

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
