// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AllocationModule.PrimaryAllocationByFilterAllocationPlugins;

namespace ENTiger.ENCollect.AllocationModule
{
    /// <summary>
    /// 
    /// </summary>
    public class PrimaryAllocationByFilterSequence : FlexiBusinessRuleSequenceBase<PrimaryAllocationByFilterDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public PrimaryAllocationByFilterSequence()
        {
            
            this.Add<ValidatePrimaryAllocation>(); 
        }
    }
}
