// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using ENTiger.ENCollect.AllocationModule.SecondaryAllocationByFilterAllocationPlugins;
using ENTiger.ENCollect.PreBus.Allocation.Plugins.SecondaryValidateUnAllocationAccess;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AllocationModule
{
    /// <summary>
    /// 
    /// </summary>
    public class SecondaryUnAllocationByBatchSequence : FlexiBusinessRuleSequenceBase<SecondaryUnAllocationByBatchDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public SecondaryUnAllocationByBatchSequence()
        {
            this.Add<ValidateUnAllocationAccess>();

            this.Add<ValidateSecondaryUnAllocation>();
        }
    }
}
