// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AllocationModule.SecondaryAllocationByBatchAllocationPlugins;

namespace ENTiger.ENCollect.AllocationModule
{
    /// <summary>
    /// 
    /// </summary>
    public class SecondaryAllocationByBatchSequence : FlexiBusinessRuleSequenceBase<SecondaryAllocationByBatchDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public SecondaryAllocationByBatchSequence()
        {
            
            this.Add<ValidateSecondaryAllocation>(); 
        }
    }
}
