// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionBatchesModule.AddCollectionBatchCollectionBatchesPlugins;

namespace ENTiger.ENCollect.CollectionBatchesModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AddCollectionBatchSequence : FlexiBusinessRuleSequenceBase<AddCollectionBatchDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AddCollectionBatchSequence()
        {
            
            this.Add<ValidateCollectionBatch>(); 
        }
    }
}
