// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyModule.AddAgencyAgencyPlugins;

namespace ENTiger.ENCollect.AgencyModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AddAgencySequence : FlexiBusinessRuleSequenceBase<AddAgencyDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AddAgencySequence()
        {
            
            this.Add<CheckDuplicateMobile>(); this.Add<CheckDuplicateAgency>(); this.Add<CheckDuplicateEmail>(); this.Add<ValidateFile>();
        }
    }
}
