// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyModule.agencygetimageAgencyPlugins;

namespace ENTiger.ENCollect.AgencyModule
{
    /// <summary>
    /// 
    /// </summary>
    public class agencygetimageSequence : FlexiBusinessRuleSequenceBase<agencygetimageDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public agencygetimageSequence()
        {            
            this.Add<ValidateAgencyInputFileFormat>(); 
            this.Add<ValidateAgencyAccesToFile>(); 
            this.Add<ValidateDownloadFile>(); 
            this.Add<AgencyDownloadFile>(); 
        }
    }
}
