// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyModule.ApproveAgencyWithDeferralAgencyPlugins;

namespace ENTiger.ENCollect.AgencyModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ApproveAgencyWithDeferralSequence : FlexiBusinessRuleSequenceBase<ApproveAgencyWithDeferralDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ApproveAgencyWithDeferralSequence()
        {
            
            this.Add<ValidateUserAcessToApproveAgnecy>(); 
        }
    }
}
