// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyModule.ApproveCollectionAgencyAgencyPlugins;

namespace ENTiger.ENCollect.AgencyModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ApproveCollectionAgencySequence : FlexiBusinessRuleSequenceBase<ApproveCollectionAgencyDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ApproveCollectionAgencySequence()
        {
            
            this.Add<ValidateUserToApproveAgency>(); 
        }
    }
}
