// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;
using ENTiger.ENCollect.DomainModels;
using ENTiger.ENCollect;
using Microsoft.Extensions.Options;
using System.IO.Abstractions;

namespace ENTiger.ENCollect.AccountsModule.AccountImportAccountsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateAccountImport : FlexiBusinessRuleBase, IFlexiBusinessRule<AccountImportDataPacket>
    {
        public override string Id { get; set; } = "3a13af91aab01c7f66d48ff74a79c20b";
        public override string FriendlyName { get; set; } = "ValidateAccountImport";

        protected readonly ILogger<ValidateAccountImport> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileValidationUtility _fileValidationUtility;
        private readonly FilePathSettings _fileSettings;
        private readonly IFileSystem _fileSystem;
        public ValidateAccountImport(ILogger<ValidateAccountImport> logger, IRepoFactory repoFactory, IFileValidationUtility fileValidationUtility, IOptions<FilePathSettings> fileSettings, IFileSystem fileSystem)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileValidationUtility = fileValidationUtility;
            _fileSettings = fileSettings.Value;
            _fileSystem = fileSystem;
        }

        public virtual async Task Validate(AccountImportDataPacket packet)
        {
            string _filepath = _fileSystem.Path.Combine(_fileSettings.BasePath, _fileSettings.IncomingPath);
            if (!_fileValidationUtility.CheckIfFileExists(_filepath, packet.Dto.filename))
            {
                packet.AddError("Error", "File Not Found/Uploaded");
            }
            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
