// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CommunicationModule.UpdateTriggerCommunicationPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateTriggerDetails : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateTriggerDataPacket>
    {
        public override string Id { get; set; } = "3a1a71241f77920ea3110283a020762a";
        public override string FriendlyName { get; set; } = "ValidateTriggerDetails";

        protected readonly ILogger<ValidateTriggerDetails> _logger;
        protected readonly RepoFactory _repoFactory;

        public ValidateTriggerDetails(ILogger<ValidateTriggerDetails> logger, RepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateTriggerDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("key", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
