// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyModule.EditCollectionAgencyAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AgencyCheckDuplicateEmailForEdit : FlexiBusinessRuleBase, IFlexiBusinessRule<EditCollectionAgencyDataPacket>
    {
        public override string Id { get; set; } = "3a1317a22c6abfdbb85b0e3c4e86852d";
        public override string FriendlyName { get; set; } = "AgencyCheckDuplicateEmailForEdit";

        protected readonly ILogger<AgencyCheckDuplicateEmailForEdit> _logger;
        protected readonly IRepoFactory _repoFactory;

        public AgencyCheckDuplicateEmailForEdit(ILogger<AgencyCheckDuplicateEmailForEdit> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(EditCollectionAgencyDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationOrg>()
                                        .Where(p => p.PrimaryEMail == packet.Dto.PrimaryEMail)
                                        .FirstOrDefaultAsync();

            if (PartyExists != null && PartyExists.Id != packet.Dto.Id)
            {
                packet.AddError("Error", "Email Id already exists");
            }
        }
    }
}
