// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyModule.EditCollectionAgencyAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AgencyCheckDuplicateMobileNumber : FlexiBusinessRuleBase, IFlexiBusinessRule<EditCollectionAgencyDataPacket>
    {
        public override string Id { get; set; } = "3a1317a220832cfb67730df58512cfc1";
        public override string FriendlyName { get; set; } = "AgencyCheckDuplicateMobileNumber";

        protected readonly ILogger<AgencyCheckDuplicateMobileNumber> _logger;
        protected readonly IRepoFactory _repoFactory;

        public AgencyCheckDuplicateMobileNumber(ILogger<AgencyCheckDuplicateMobileNumber> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(EditCollectionAgencyDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationOrg>()
                                        .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber)
                                        .FirstOrDefaultAsync();

            if (PartyExists != null && PartyExists.Id != packet.Dto.Id)
            {
                packet.AddError("Error", "Mobile Number already exists");
            }
        }
    }
}
