# Simple definition to run boman-cli tool
# Make sure you have boman.yaml file in your repo

trigger:
- dev

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' # 3.6,3.7,3.9 
- script: |
    sudo python3 -m pip install --upgrade pip # optional
    sudo python3 -m pip install boman-cli==2.4.1
    sudo boman-cli -a run -config ./boman_dast.yaml -zap_arg '-z "-config scanner.maxScanDurationInMins=50"'
  displayName: 'install boman-cli and run scan'

