// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AccountsModule.UpdateRoleBasedSearchAccountsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateInput : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateRoleBasedSearchDataPacket>
    {
        public override string Id { get; set; } = "3a185d06fdc9f6f84aeda784523fc377";
        public override string FriendlyName { get; set; } = "Validate";

        protected readonly ILogger<ValidateInput> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateInput(ILogger<ValidateInput> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateRoleBasedSearchDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("key", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
