// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CompanyUsersModule.EnableCompanyUsersCompanyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateUsers : FlexiBusinessRuleBase, IFlexiBusinessRule<EnableCompanyUsersDataPacket>
    {
        public override string Id { get; set; } = "3a1a0a28d337710fd80d5832ddd7c02e";
        public override string FriendlyName { get; set; } = "ValidateUsers";

        protected readonly ILogger<ValidateUsers> _logger;
        protected readonly RepoFactory _repoFactory;

        public ValidateUsers(ILogger<ValidateUsers> logger, RepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(EnableCompanyUsersDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("key", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
