// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyUsersModule
{
    public partial class ProcessAgencyUsersService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(GetAgentImageCommand cmd)
        {

            GetAgentImagePostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetAgentImagePostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetAgentImagePostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetAgentImagePostBusSequence, GetAgentImagePostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
