// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyUsersModule
{
    public partial class ProcessAgencyUsersService : ProcessFlexServiceBridge
    {
        public string Id { get; set; }
        protected virtual async Task ProcessCommand(UploadCommand cmd)
        {

            UploadPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<UploadPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<UploadPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<UploadPostBusSequence, UploadPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));

            Id = packet.Id;
        }
    }
}
