// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using ENCollect.Security;
using Sumeru.Flex;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace ENTiger.ENCollect.ApplicationUsersModule.MobileForgotPasswordApplicationUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateUser : FlexiBusinessRuleBase, IFlexiBusinessRule<MobileForgotPasswordDataPacket>
    {
        public override string Id { get; set; } = "3a1347a6ef21f4a9157bf48edae07b01";
        public override string FriendlyName { get; set; } = "ValidateUser";

        protected readonly ILogger<ValidateUser> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected readonly IUserUtility _userUtility;

        public ValidateUser(ILogger<ValidateUser> logger, IRepoFactory repoFactory, IUserUtility userUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _userUtility = userUtility;
        }

        public virtual async Task Validate(MobileForgotPasswordDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            if (!packet.HasError)
            {
                string Email = string.Empty;
                var aesGcmCrypto = new AesGcmCrypto();
                var aesGcmKey = Encoding.UTF8.GetBytes(packet.Key);

                Email = aesGcmCrypto.Decrypt(packet.Dto.Email, aesGcmKey);
                packet.Dto.Email = Email;
                var user = await _repoFactory.GetRepo().FindAll<ApplicationUser>().Where(a => a.PrimaryEMail == Email).FirstOrDefaultAsync();
                if (user == null)
                {
                    packet.AddError("Error", "Invalid User");
                }
                else
                {  
                    string errormessage = await _userUtility.ValidateUserStatus(user, packet.Dto);

                    if (!string.IsNullOrEmpty(errormessage))
                    {
                        packet.AddError("Error", errormessage);
                    }
                }
            }
        }
    }
}
