// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyModule.agencygetimageAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateAgencyInputFileFormat : FlexiBusinessRuleBase, IFlexiBusinessRule<agencygetimageDataPacket>
    {
        public override string Id { get; set; } = "3a1338a184976e44c93f0a03f61ddd18";
        public override string FriendlyName { get; set; } = "ValidateAgencyInputFileFormat";

        protected readonly ILogger<ValidateAgencyInputFileFormat> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateAgencyInputFileFormat(ILogger<ValidateAgencyInputFileFormat> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(agencygetimageDataPacket packet)
        {
            Regex regularexpression = new Regex(@"^[a-zA-Z0-9_ ][\w\.]+[a-zA-Z]$", RegexOptions.IgnoreCase);
            var match = regularexpression.Match(packet.Dto.FileName);
            if (match.Success == false)
            {
                packet.AddError("Error", "Filename should not contain special characters");                
            }

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
