// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyUsersModule.UploadAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UploadFile : FlexiBusinessRuleBase, IFlexiBusinessRule<UploadDataPacket>
    {
        public override string Id { get; set; } = "3a136152030c45d5eeb284698ce7a0db";
        public override string FriendlyName { get; set; } = "UploadFile";

        protected readonly ILogger<UploadFile> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileTransferUtility _fileTransferUtility;

        public UploadFile(ILogger<UploadFile> logger, IRepoFactory repoFactory, IFileTransferUtility fileTransferUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileTransferUtility = fileTransferUtility;
        }

        public virtual async Task Validate(UploadDataPacket packet)
        {
            if (!packet.HasError)
            {
                packet.OutputDto = await _fileTransferUtility.SaveUploadFileAsync(packet.Dto.file);
            }

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
