// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ENTiger.ENCollect.DomainModels;

namespace ENTiger.ENCollect.AgencyUsersModule.UploadAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateFile : FlexiBusinessRuleBase, IFlexiBusinessRule<UploadDataPacket>
    {
        public override string Id { get; set; } = "3a1361520a7af216677638e0ccd417c5";
        public override string FriendlyName { get; set; } = "ValidateFile";

        protected readonly ILogger<ValidateFile> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileValidationUtility _fileValidationUtility;

        public ValidateFile(ILogger<ValidateFile> logger, IRepoFactory repoFactory, IFileValidationUtility fileValidationUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileValidationUtility = fileValidationUtility;
        }

        public virtual async Task Validate(UploadDataPacket packet)
        {
            IFormFile file = packet.Dto.file;
            if (!_fileValidationUtility.ValidateUploadFile(file, out string errorMessage))
            {
                packet.AddError("Error", errorMessage);
            }

            Regex regularexpression = new Regex(@"^[a-zA-Z0-9_\.]+$", RegexOptions.IgnoreCase);
            var match = regularexpression.Match(file.FileName);
            if (match.Success == false)
            {
                packet.AddError("Error", "File name should not contain special characters and spaces.");
            }

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
