// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.SettlementModule
{
    public partial class ProcessSettlementService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(CancelSettlementCommand cmd)
        {
            CancelSettlementPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<CancelSettlementPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<CancelSettlementPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<CancelSettlementWorkflowPostBusSequence, CancelSettlementPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));

        }

    }
}
