// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;

using Sumeru.Flex;

namespace ENTiger.ENCollect.SettlementModule
{
    public partial class ProcessSettlementService : ProcessFlexServiceBridge
    {
        public string ReferenceId { get; set; }
        public string Key { get; set; }
        protected virtual async Task ProcessCommand(UpdateSettlementCommand cmd)
        {

            UpdateSettlementPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<UpdateSettlementPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<UpdateSettlementPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<UpdateSettlementWorkflowPostBusSequence, UpdateSettlementPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));

        }

    }
}
