// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AccountsModule.GetAccountBalanceDetailsAccountsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class GetAccountBalanceDetails : FlexiBusinessRuleBase, IFlexiBusinessRule<GetAccountBalanceDetailsDataPacket>
    {
        public override string Id { get; set; } = "3a151b482cb808f445c9700e2c7f6ae3";
        public override string FriendlyName { get; set; } = "GetAccountBalanceDetails";

        protected readonly ILogger<GetAccountBalanceDetails> _logger;
        protected readonly IRepoFactory _repoFactory;

        public GetAccountBalanceDetails(ILogger<GetAccountBalanceDetails> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(GetAccountBalanceDetailsDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("key", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
