// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.GeoTagModule.SearchUsersByGeoTagGeoTagPlugins;

namespace ENTiger.ENCollect.GeoTagModule
{
    /// <summary>
    /// 
    /// </summary>
    public class SearchUsersByGeoTagSequence : FlexiBusinessRuleSequenceBase<SearchUsersByGeoTagDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public SearchUsersByGeoTagSequence()
        {
            
            this.Add<ValidateUser>(); this.Add<SearchUsers>();
        }
    }
}
