// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.ApplicationUsersModule.GetKeyApplicationUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateTenant : FlexiBusinessRuleBase, IFlexiBusinessRule<GetKeyDataPacket>
    {
        public override string Id { get; set; } = "3a12db0dc990c32225d1db23170d4bae";
        public override string FriendlyName { get; set; } = "ValidateTenant";

        protected readonly ILogger<ValidateTenant> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateTenant(ILogger<ValidateTenant> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(GetKeyDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
