// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.TreatmentModule.UpdateTreatmentsSequenceTreatmentPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateTreatments : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateTreatmentsSequenceDataPacket>
    {
        public override string Id { get; set; } = "3a14632add4246a3b28f2322eb7b9f31";
        public override string FriendlyName { get; set; } = "ValidateTreatments";

        protected readonly ILogger<ValidateTreatments> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateTreatments(ILogger<ValidateTreatments> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateTreatmentsSequenceDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
