// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CollectionsModule.SendPaymentCopyViaSMSCollectionsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidatePayment : FlexiBusinessRuleBase, IFlexiBusinessRule<SendPaymentCopyViaSMSDataPacket>
    {
        public override string Id { get; set; } = "3a138ee1453980d952896d582708f26f";
        public override string FriendlyName { get; set; } = "ValidatePayment";

        protected readonly ILogger<ValidatePayment> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidatePayment(ILogger<ValidatePayment> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(SendPaymentCopyViaSMSDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
