// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.PayInSlipsModule.UpdatePayInSlipPayInSlipsPlugins;

namespace ENTiger.ENCollect.PayInSlipsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdatePayInSlipSequence : FlexiBusinessRuleSequenceBase<UpdatePayInSlipDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdatePayInSlipSequence()
        {
            
            this.Add<ValidatePayInSlip>(); 
        }
    }
}
