// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.AccountsModule.AccountImportAccountsPlugins;
using ENTiger.ENCollect.DomainModels;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Sumeru.Flex;
using System.IO.Abstractions;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CollectionsModule.CollectionBulkUploadCollectionsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateIfFileExists : FlexiBusinessRuleBase, IFlexiBusinessRule<CollectionBulkUploadDataPacket>
    {
        public override string Id { get; set; } = "3a182aa7f04c30c05b1246ebb8184c51";
        public override string FriendlyName { get; set; } = "ValidateBulkUpload";

        protected readonly ILogger<ValidateIfFileExists> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileValidationUtility _fileValidationUtility;
        private readonly FilePathSettings _fileSettings;
        private readonly IFileSystem _fileSystem;
        public ValidateIfFileExists(
            ILogger<ValidateIfFileExists> logger, 
            IRepoFactory repoFactory, 
            IFileValidationUtility fileValidationUtility, 
            IOptions<FilePathSettings> fileSettings, 
            IFileSystem fileSystem)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileValidationUtility = fileValidationUtility;
            _fileSettings = fileSettings.Value;
            _fileSystem = fileSystem;
        }

        public virtual async Task Validate(CollectionBulkUploadDataPacket packet)
        {
            string _filepath = _fileSystem.Path.Combine(_fileSettings.BasePath, _fileSettings.IncomingPath);
            if (!_fileValidationUtility.CheckIfFileExists(_filepath, packet.Dto.FileName))
            {
                packet.AddError("Error", "File Not Found/Uploaded");
            }

            await Task.CompletedTask;
        }

    }
}
