// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.GeoTagModule.AddLoginGeoTagGeoTagPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateLoginGeoTag : FlexiBusinessRuleBase, IFlexiBusinessRule<AddLoginGeoTagDataPacket>
    {
        public override string Id { get; set; } = "3a13679b6fd8169dc960b80bc37a73cb";
        public override string FriendlyName { get; set; } = "ValidateLoginGeoTag";

        protected readonly ILogger<ValidateLoginGeoTag> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateLoginGeoTag(ILogger<ValidateLoginGeoTag> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AddLoginGeoTagDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
