// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyUsersModule.UpdateAgentAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckDuplicateEmailBeforeUpdate : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateAgentDataPacket>
    {
        public override string Id { get; set; } = "3a12e7a1364b097eafdb071fb018a2f0";
        public override string FriendlyName { get; set; } = "CheckDuplicateEmailBeforeUpdate";

        protected readonly ILogger<CheckDuplicateEmailBeforeUpdate> _logger;
        protected readonly IRepoFactory _repoFactory;

        public CheckDuplicateEmailBeforeUpdate(ILogger<CheckDuplicateEmailBeforeUpdate> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateAgentDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
