// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CollectionsModule.AcknowledgeCollectionsCollectionsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateCollections : FlexiBusinessRuleBase, IFlexiBusinessRule<AcknowledgeCollectionsDataPacket>
    {
        public override string Id { get; set; } = "3a138f3b8bed58e086b91b61d2901790";
        public override string FriendlyName { get; set; } = "ValidateCollections";

        protected readonly ILogger<ValidateCollections> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateCollections(ILogger<ValidateCollections> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AcknowledgeCollectionsDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
