// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyUsersModule.RejectAgentAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckCreatedBy : FlexiBusinessRuleBase, IFlexiBusinessRule<RejectAgentDataPacket>
    {
        public override string Id { get; set; } = "3a12e79e4d2c7c153a84a1e9c8435c68";
        public override string FriendlyName { get; set; } = "CheckCreatedBy";

        protected readonly ILogger<CheckCreatedBy> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected FlexAppContextBridge? _flexAppContext;
        public CheckCreatedBy(ILogger<CheckCreatedBy> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(RejectAgentDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _flexAppContext = packet.Dto.GetAppContext();
            _repoFactory.Init(packet.Dto);

            string loggedInUserId = _flexAppContext.UserId;
            List<ApplicationUser> users;
            List<string> ids = packet.Dto.AgentIds;

            users = await _repoFactory.GetRepo().FindAll<ApplicationUser>().ByTFlexIds(ids).ToListAsync();

            foreach (var user in users)
            {
                if ((user.CreatedBy == loggedInUserId && user.CreatedDate.DateTime.Subtract(user.LastModifiedDate.DateTime).Seconds == 0) ||
                        (user.LastModifiedBy == loggedInUserId && user.CreatedDate.DateTime.Subtract(user.LastModifiedDate.DateTime).Seconds != 0))
                {
                    packet.AddError("Error", "You do not have permission to reject");
                }
            }
        }
    }
}
