// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.DevicesModule.ValidateRegisterDeviceOtpDevicesPlugins;

namespace ENTiger.ENCollect.DevicesModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ValidateRegisterDeviceOtpSequence : FlexiBusinessRuleSequenceBase<ValidateRegisterDeviceOtpDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ValidateRegisterDeviceOtpSequence()
        {
            
            this.Add<VerifyAndUpdateDeviceOTP>(); 
        }
    }
}
