// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CompanyUsersModule.AddCompanyUserCompanyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckDuplicateMobile : FlexiBusinessRuleBase, IFlexiBusinessRule<AddCompanyUserDataPacket>
    {
        public override string Id { get; set; } = "3a12cbc5ecddc2ff61165a98d27b2613";
        public override string FriendlyName { get; set; } = "CheckDuplicateMobile";

        protected readonly ILogger<CheckDuplicateMobile> _logger;
        protected readonly IRepoFactory _repoFactory;

        public CheckDuplicateMobile(ILogger<CheckDuplicateMobile> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AddCompanyUserDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationUser>()
                                        .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber)
                                        .FirstOrDefaultAsync();

            if (PartyExists != null)
            {
                packet.AddError("Error", "Mobile Number already exists");
            }
        }
    }
}
