// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyModule
{
    public partial class ProcessAgencyService : ProcessFlexServiceBridge
    {
        public string Id { get; set; }
        protected virtual async Task ProcessCommand(AgencyUploadCommand cmd)
        {

            AgencyUploadPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<AgencyUploadPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<AgencyUploadPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<AgencyUploadPostBusSequence, AgencyUploadPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));

            Id = packet.Id;
        }
    }
}
