// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyUsersModule.PrintIdCardAgencyUsersPlugins;

namespace ENTiger.ENCollect.AgencyUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class PrintIdCardSequence : FlexiBusinessRuleSequenceBase<PrintIdCardDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public PrintIdCardSequence()
        {
            
            this.Add<ValidateUser>(); 
        }
    }
}
