// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AgencyUsersModule.UpdateAgentAgencyUsersPlugins;

namespace ENTiger.ENCollect.AgencyUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateAgentSequence : FlexiBusinessRuleSequenceBase<UpdateAgentDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdateAgentSequence()
        {
            
            this.Add<CheckDuplicateEmailBeforeUpdate>(); this.Add<CheckDuplicateMobileBeforeUpdate>();  this.Add<CheckPincodeBeforeUpdate>(); this.Add<ValidateFile>(); this.Add<CheckWalletLimit>();
        }
    }
}
