// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.PayInSlipsModule.UpdatePayInSlipPayInSlipsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidatePayInSlip : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdatePayInSlipDataPacket>
    {
        public override string Id { get; set; } = "3a1386509d5392779cdf90df903e7cb1";
        public override string FriendlyName { get; set; } = "ValidatePayInSlip";

        protected readonly ILogger<ValidatePayInSlip> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidatePayInSlip(ILogger<ValidatePayInSlip> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdatePayInSlipDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            var payinslip = await _repoFactory.GetRepo().FindAll<PayInSlip>()
                                        .Where(x => x.CMSPayInSlipNo == packet.Dto.CMSPayInSlipNo)
                                        .FirstOrDefaultAsync();
            if (payinslip != null)
            {
                packet.AddError("Error", "PayInSlip number already used");
            }
        }
    }
}
