// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.AccountsModule.UpdateLoanAccountNoteAccountsPlugins;

namespace ENTiger.ENCollect.AccountsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateLoanAccountNoteSequence : FlexiBusinessRuleSequenceBase<UpdateLoanAccountNoteDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdateLoanAccountNoteSequence()
        {
            
            this.Add<ValidateGeneral>(); 
        }
    }
}
