// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    public partial class ProcessApplicationUsersService : ProcessFlexServiceBridge
    {
        public string ReferenceId { get; set; }
        public string Key { get; set; }
        protected virtual async Task ProcessCommand(GetKeyCommand cmd)
        {

            GetKeyPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetKeyPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetKeyPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetKeyPostBusSequence, GetKeyPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));

            ReferenceId = packet.ReferenceId;
            Key = packet.Key;
        }

    }
}
