// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyModule.RejectAgencyAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateUserAcessToRejectAgency : FlexiBusinessRuleBase, IFlexiBusinessRule<RejectAgencyDataPacket>
    {
        public override string Id { get; set; } = "3a13183dba1756e8e78677874672e24f";
        public override string FriendlyName { get; set; } = "ValidateUserAcessToRejectAgency";

        protected readonly ILogger<ValidateUserAcessToRejectAgency> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected List<Agency>? _model;
        protected FlexAppContextBridge? _flexAppContext;
        public ValidateUserAcessToRejectAgency(ILogger<ValidateUserAcessToRejectAgency> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(RejectAgencyDataPacket packet)
        {
            _flexAppContext = packet.Dto.GetAppContext();  //do not remove this line

            string loggedInUserId = _flexAppContext.UserId;
            _repoFactory.Init(packet.Dto);

            _model = await _repoFactory.GetRepo().FindAll<Agency>()
                                .Where(m => packet.Dto.AgencyIds.Contains(m.Id))
                                .ToListAsync();

            foreach (var agency in _model)
            {
                if (agency.CreatedBy == loggedInUserId)
                {
                    packet.AddError("Error", "You do not have permission to approve.");
                }
            }
        }
    }
}
