// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CollectionsModule
{
    public partial class ProcessCollectionsService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(GetCollectionImageCommand cmd)
        {

            GetCollectionImagePostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetCollectionImagePostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetCollectionImagePostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetCollectionImagePostBusSequence, GetCollectionImagePostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
