// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.AddUserAttendanceApplicationUsersPlugins;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AddUserAttendanceSequence : FlexiBusinessRuleSequenceBase<AddUserAttendanceDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AddUserAttendanceSequence()
        {
            
            this.Add<AddUserAttendance>(); 
        }
    }
}
