// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.AzureLoginApplicationUsersPlugins;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AzureLoginSequence : FlexiBusinessRuleSequenceBase<AzureLoginDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AzureLoginSequence()
        {            
            this.Add<ValidateKey>(); this.Add<AzureLogin>(); 
        }
    }
}
