// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.LoginApplicationUsersPlugins;
using ENTiger.ENCollect.AgencyUsersModule.PrintIdCardAgencyUsersPlugins;
using ENTiger.ENCollect.PreBus.ApplicationUsers.Plugins.Login;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class LoginSequence : FlexiBusinessRuleSequenceBase<LoginDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public LoginSequence()
        {
            
            this.Add<ValidateCaptcha>(); this.Add<ValidateKey>();
            this.Add<ValidateLoginUser>(); 
            this.Add<Login>();
        }
    }
}
