// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.MobileForgotPasswordApplicationUsersPlugins;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class MobileForgotPasswordSequence : FlexiBusinessRuleSequenceBase<MobileForgotPasswordDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public MobileForgotPasswordSequence()
        {
            this.Add<ValidateKey>(); this.Add<ValidateUser>(); 
        }
    }
}
