// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.ResetPasswordApplicationUsersPlugins;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ResetPasswordSequence : FlexiBusinessRuleSequenceBase<ResetPasswordDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ResetPasswordSequence()
        {
            
            this.Add<ValidateKey>(); this.Add<ResetPassword>(); 
        }
    }
}
