// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.ApplicationUsersModule.UpdateCodeOfConductApplicationUsersPlugins;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateCodeOfConductSequence : FlexiBusinessRuleSequenceBase<UpdateCodeOfConductDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdateCodeOfConductSequence()
        {
            
            this.Add<IsValid>(); 
        }
    }
}
