// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyModule.AddAgencyAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckDuplicateMobile : FlexiBusinessRuleBase, IFlexiBusinessRule<AddAgencyDataPacket>
    {
        public override string Id { get; set; } = "3a12d59f503d54df760c72a6e1629458";
        public override string FriendlyName { get; set; } = "CheckDuplicateMobile";

        protected readonly ILogger<CheckDuplicateMobile> _logger;
        protected readonly IRepoFactory _repoFactory;

        public CheckDuplicateMobile(ILogger<CheckDuplicateMobile> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AddAgencyDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationOrg>()
                                    .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber)
                                    .FirstOrDefaultAsync();

            if (PartyExists != null)
            {
                packet.AddError("Error", "Mobile Number already exists");
            }
        }
    }
}
