// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;

namespace ENTiger.ENCollect.ApplicationUsersModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ResetPasswordPostBusSequence : FlexiPluginSequenceBase<ResetPasswordPostBusDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ResetPasswordPostBusSequence()
        {
            this.Add<ResetPasswordPlugin>(); 
        }
    }
}
