// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.TreatmentModule
{
    public partial class ProcessTreatmentService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(GetTreatmentReportFileCommand cmd)
        {

            GetTreatmentReportFilePostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetTreatmentReportFilePostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetTreatmentReportFilePostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetTreatmentReportFilePostBusSequence, GetTreatmentReportFilePostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
