// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.DevicesModule
{
    public partial class ProcessDevicesService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(ValidateRegisterDeviceOtpCommand cmd)
        {

            ValidateRegisterDeviceOtpPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<ValidateRegisterDeviceOtpPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<ValidateRegisterDeviceOtpPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<ValidateRegisterDeviceOtpPostBusSequence, ValidateRegisterDeviceOtpPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
