// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CommonModule.UploadFileCommonPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UploadFile : FlexiBusinessRuleBase, IFlexiBusinessRule<UploadFileDataPacket>
    {
        public override string Id { get; set; } = "3a135d1c4681bd8ee9e3d87457d68500";
        public override string FriendlyName { get; set; } = "UploadFile";

        protected readonly ILogger<ValidateFile> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly IFileTransferUtility _fileTransferUtility;
        public UploadFile(ILogger<ValidateFile> logger, IRepoFactory repoFactory, IFileTransferUtility fileTransferUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileTransferUtility = fileTransferUtility;
        }

        public virtual async Task Validate(UploadFileDataPacket packet)
        {
            if (!packet.HasError)
            {
                packet.OutputDto = await _fileTransferUtility.SaveUploadFileAsync(packet.Dto.file);
            }
        }
    }
}
