// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionsModule.AddPhysicalCollectionCollectionsPlugins;
using ENTiger.ENCollect.CollectionsModule.AddCollectionCollectionsPlugins;

namespace ENTiger.ENCollect.CollectionsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AddPhysicalCollectionSequence : FlexiBusinessRuleSequenceBase<AddPhysicalCollectionDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AddPhysicalCollectionSequence()
        {

            this.Add<CheckUserPhysicalCollectionLimit>(); this.Add<ValidateAccount>(); this.Add<CheckDuplicatePhysicalReceipt>(); this.Add<ValidateFile>();
        }
    }
}
