// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionsModule.GetCollectionImageCollectionsPlugins;

namespace ENTiger.ENCollect.CollectionsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class GetCollectionImageSequence : FlexiBusinessRuleSequenceBase<GetCollectionImageDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public GetCollectionImageSequence()
        {
            this.Add<ValidateFile>(); this.Add<CheckFileAccess>(); 
        }
    }
}
