// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionsModule.GetCollectionFileCollectionsPlugins;

namespace ENTiger.ENCollect.CollectionsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class GetCollectionFileSequence : FlexiBusinessRuleSequenceBase<GetCollectionFileDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public GetCollectionFileSequence()
        {

            this.Add<ValidateFile>(); this.Add<CheckFileAccess>(); 
        }
    }
}
