// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionsModule.SendPaymentCopyViaEmailCollectionsPlugins;

namespace ENTiger.ENCollect.CollectionsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class SendPaymentCopyViaEmailSequence : FlexiBusinessRuleSequenceBase<SendPaymentCopyViaEmailDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public SendPaymentCopyViaEmailSequence()
        {
            
            this.Add<ValidatePayment>(); 
        }
    }
}
