// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CollectionsModule.SendPaymentLinkCollectionsPlugins;

namespace ENTiger.ENCollect.CollectionsModule
{
    /// <summary>
    /// 
    /// </summary>
    public class SendPaymentLinkSequence : FlexiBusinessRuleSequenceBase<SendPaymentLinkDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public SendPaymentLinkSequence()
        {
            this.Add<ValidateAccount>(); this.Add<GenerateReceipt>(); 
        }
    }
}
