// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CommunicationModule.UpdateTriggerCommunicationPlugins;

namespace ENTiger.ENCollect.CommunicationModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateTriggerSequence : FlexiBusinessRuleSequenceBase<UpdateTriggerDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdateTriggerSequence()
        {
            
            this.Add<ValidateTriggerDetails>(); 
        }
    }
}
