// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyUsersModule.AddAgentAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckDuplicateMobile : FlexiBusinessRuleBase, IFlexiBusinessRule<AddAgentDataPacket>
    {
        public override string Id { get; set; } = "3a12d148d28ff06a61150794db1c9395";
        public override string FriendlyName { get; set; } = "CheckDuplicateMobile";

        protected readonly ILogger<CheckDuplicateMobile> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected FlexAppContextBridge? _flexAppContext;

        public CheckDuplicateMobile(ILogger<CheckDuplicateMobile> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AddAgentDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _flexAppContext = packet.Dto.GetAppContext();
            _repoFactory.Init(packet.Dto);

            if (!packet.HasError)
            {
                if (!string.IsNullOrEmpty(packet.Dto.PrimaryEMail))
                {

                    var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationUser>()
                                            .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber &&
                                                        p.GetType() == typeof(CompanyUser))
                                            .FirstOrDefaultAsync();

                    if (PartyExists != null)
                    {
                        packet.AddError("Error", "Staffuser already exist for same mobile no.");
                    }
                }
                if (!packet.HasError)
                {
                    if (string.IsNullOrEmpty(packet.Dto.overwriteAgentId))
                    {
                        var PartyExists = await _repoFactory.GetRepo().FindAll<AgencyUser>()
                                                .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber)
                                                .FirstOrDefaultAsync();

                        if (PartyExists != null)
                        {
                            packet.AddError("Error", "Mobile Number already exists");
                        }
                    }
                    else
                    {
                        AgencyUserWorkflowState state = WorkflowStateFactory.GetCollectionAgencyUserWFState("disabled");

                        var PartyExists = await _repoFactory.GetRepo().FindAll<AgencyUser>()
                                                .IncludeAgencyUserWorkflow()
                                                .Where(p => p.PrimaryMobileNumber == packet.Dto.PrimaryMobileNumber &&
                                                        p.Id != packet.Dto.overwriteAgentId &&
                                                        p.AgencyUserWorkflowState.Name != state.Name &&
                                                        p.UserId != null && p.IsDeleted == false)
                                                .FirstOrDefaultAsync();

                        if (PartyExists != null)
                        {
                            packet.AddError("Error", "Mobile Number already exists");
                        }
                    }
                }
            }
            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
