// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;

namespace ENTiger.ENCollect.SettlementModule
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateSettlementPostBusSequence : FlexiPluginSequenceBase<UpdateSettlementPostBusDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public UpdateSettlementPostBusSequence()
        {
           this.Add<UpdateSettlementPlugin>(); 
        }
    }
}
