// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CommonModule.GetImageCommonPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckFileAccess : FlexiBusinessRuleBase, IFlexiBusinessRule<GetImageDataPacket>
    {
        public override string Id { get; set; } = "3a1361dbab25d1104da851bf3a2f9caf";
        public override string FriendlyName { get; set; } = "CheckFileAccess";

        protected readonly ILogger<CheckFileAccess> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected FlexAppContextBridge? _flexAppContext;

        public CheckFileAccess(ILogger<CheckFileAccess> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(GetImageDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);
            _flexAppContext = packet.Dto.GetAppContext();  //do not remove this line

            string userId = _flexAppContext.UserId;

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            List<string> filesList = new List<string>();
            var user = await _repoFactory.GetRepo().Find<ApplicationUser>(userId).FirstOrDefaultAsync();
            if (user.GetType().Name.Contains("agencyuser", StringComparison.OrdinalIgnoreCase))
            {
                var agencyUser = await _repoFactory.GetRepo().Find<AgencyUser>(userId).FirstOrDefaultAsync();

                var users = await _repoFactory.GetRepo().FindAll<AgencyUser>()
                                    .Where(x => x.AgencyId == agencyUser.AgencyId)
                                    .IncludeAgencyUserIdentifications()
                                    .IncludeAgencyUserIdentificationDocs()
                                    .ToListAsync();

                if (users != null && users.Count() > 0)
                {
                    filesList.AddRange(users.Select(x => x.ProfileImage).ToList());

                    foreach (var obj in users)
                    {
                        var docs = obj?.AgencyUserIdentifications;
                        var files = docs?.Select(x => x.TFlexIdentificationDocs).ToList();
                        var fileNames = files?.Select(x => x.FirstOrDefault()?.FileName).ToList();
                        if (fileNames != null && fileNames.Count() > 0)
                        {
                            filesList.AddRange(fileNames.ToList());
                        }
                    }
                }

                var collections = await _repoFactory.GetRepo().FindAll<Collection>()
                                            .Where(x => x.CollectionOrgId == agencyUser.AgencyId ||
                                                        x.CreatedBy == agencyUser.Id)
                                            .ToListAsync();

                if (collections != null && collections.Count() > 0)
                {
                    filesList.AddRange(collections.Select(x => x.PayerImageName).ToList());
                    filesList.AddRange(collections.Select(x => x.ChangeRequestImageName).ToList());
                }

                if (filesList.Where(x => x != null && x.Contains(packet.Dto.FileName)).Count() == 0)
                {
                    _logger.LogError("CheckFileAccess : Access Denied");
                    packet.AddError("Error", "Access Denied");
                }
            }
        }
    }
}
