// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.PayInSlipsModule.AckPayInSlipPayInSlipsPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidatePayInSlip : FlexiBusinessRuleBase, IFlexiBusinessRule<AckPayInSlipDataPacket>
    {
        public override string Id { get; set; } = "3a138ab42611dda2d4724055d0ae29fe";
        public override string FriendlyName { get; set; } = "ValidatePayInSlip";

        protected readonly ILogger<ValidatePayInSlip> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidatePayInSlip(ILogger<ValidatePayInSlip> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(AckPayInSlipDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("Error", "ErrorMessage");


            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
