// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.CommunicationModule.DeleteTemplateCommunicationPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateTemplateBeforeDelete : FlexiBusinessRuleBase, IFlexiBusinessRule<DeleteTemplateDataPacket>
    {
        public override string Id { get; set; } = "3a13373f30b422513f6f358e11628395";
        public override string FriendlyName { get; set; } = "ValidateTemplateBeforeDelete";

        protected readonly ILogger<ValidateTemplateBeforeDelete> _logger;
        protected readonly IRepoFactory _repoFactory;

        public ValidateTemplateBeforeDelete(ILogger<ValidateTemplateBeforeDelete> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(DeleteTemplateDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            var template = await _repoFactory.GetRepo().FindAll<CommunicationTemplate>()
                                    .ByTFlexId(packet.Dto.Id)
                                    .FirstOrDefaultAsync();
            if (template == null)
            {
                packet.AddError("Error", "Invalid Template");
            }
        }
    }
}
