// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CompanyUsersModule.UpdateCompanyUserCompanyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CheckDuplicateEmailBeforeUpdate : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateCompanyUserDataPacket>
    {
        public override string Id { get; set; } = "3a12da526e456f4b2904615673d9375a";
        public override string FriendlyName { get; set; } = "CheckDuplicateEmailBeforeUpdate";

        protected readonly ILogger<CheckDuplicateEmailBeforeUpdate> _logger;
        protected readonly IRepoFactory _repoFactory;

        public CheckDuplicateEmailBeforeUpdate(ILogger<CheckDuplicateEmailBeforeUpdate> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateCompanyUserDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            _repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            var PartyExists = await _repoFactory.GetRepo().FindAll<ApplicationUser>()
                                        .Where(p => p.PrimaryEMail == packet.Dto.PrimaryEMail)
                                        .FirstOrDefaultAsync();

            if (PartyExists != null && PartyExists.Id != packet.Dto.Id)
            {
                packet.AddError("Error", "Email already exists");
            }
        }
    }
}
