// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.PublicModule.ImportAccountsPublicPlugins;

namespace ENTiger.ENCollect.PublicModule
{
    /// <summary>
    /// 
    /// </summary>
    public class ImportAccountsSequence : FlexiBusinessRuleSequenceBase<ImportAccountsDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public ImportAccountsSequence()
        {
            
            this.Add<ValidateImportAccounts>(); 
        }
    }
}
