// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.FeedbackModule.GetTrailFileFeedbackPlugins;

namespace ENTiger.ENCollect.FeedbackModule
{
    /// <summary>
    /// 
    /// </summary>
    public class GetTrailFileSequence : FlexiBusinessRuleSequenceBase<GetTrailFileDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public GetTrailFileSequence()
        {
            
            this.Add<ValidateFile>(); this.Add<CheckFileAccess>(); 
        }
    }
}
