// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with chosen option when the code will be generated next time.
// </auto-generated>

using System.Threading.Tasks;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AccountsModule
{
    public partial class ProcessAccountsService : ProcessFlexServiceBridge
    {
        protected virtual async Task ProcessCommand(GetAccountBalanceDetailsCommand cmd)
        {

            GetAccountBalanceDetailsPostBusDataPacket packet = _flexHost.GetFlexiFlowDataPacket<GetAccountBalanceDetailsPostBusDataPacket>();

            //Fill your data to datapacket here
            packet.Cmd = cmd;

            FlexiPluginSequenceBase<GetAccountBalanceDetailsPostBusDataPacket> sequence = _flexHost.GetFlexiPluginSequence<GetAccountBalanceDetailsPostBusSequence, GetAccountBalanceDetailsPostBusDataPacket>();

            await FlexiFlow.Run(sequence, packet, new FlexServiceBusContextBridge(_bus));
        }

    }
}
