// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels;
using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.CommonModule.GetLogoCommonPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateFile : FlexiBusinessRuleBase, IFlexiBusinessRule<GetLogoDataPacket>
    {
        public override string Id { get; set; } = "3a139ac88a251dbdefd0fb4671f78c51";
        public override string FriendlyName { get; set; } = "ValidateFile";

        protected readonly ILogger<ValidateFile> _logger;
        protected readonly IRepoFactory _repoFactory;
        
        private readonly IFileValidationUtility _fileValidationUtility;


        public ValidateFile(ILogger<ValidateFile> logger, IRepoFactory repoFactory, IFileValidationUtility fileValidationUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileValidationUtility = fileValidationUtility;
        }

        public virtual async Task Validate(GetLogoDataPacket packet)
        {
            if (!packet.HasError) 
            {
                if (!_fileValidationUtility.ValidateFileName(packet.Logo, out string errorMessage))
                {
                    packet.AddError("Error", errorMessage);
                }
                if (!_fileValidationUtility.ValidateDownloadFile(packet.Logo, out string message))
                {
                    packet.AddError("Error", message);
                }
            }            

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
