// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AgencyModule.ApproveAgencyWithDeferralAgencyPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateUserAcessToApproveAgnecy : FlexiBusinessRuleBase, IFlexiBusinessRule<ApproveAgencyWithDeferralDataPacket>
    {
        public override string Id { get; set; } = "3a131825bfd8427416f64c144d050baf";
        public override string FriendlyName { get; set; } = "ValidateUserAcessToApproveAgnecy";

        protected readonly ILogger<ValidateUserAcessToApproveAgnecy> _logger;
        protected readonly IRepoFactory _repoFactory;
        protected List<Agency>? _model;
        protected FlexAppContextBridge? _flexAppContext;
        public ValidateUserAcessToApproveAgnecy(ILogger<ValidateUserAcessToApproveAgnecy> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(ApproveAgencyWithDeferralDataPacket packet)
        {
            _flexAppContext = packet.Dto.GetAppContext();  //do not remove this line

            string loggedInUserId = _flexAppContext.UserId;
            _repoFactory.Init(packet.Dto);

            _model = await _repoFactory.GetRepo().FindAll<Agency>().Where(m => packet.Dto.AgencyIds.Contains(m.Id)).ToListAsync();

            foreach (var agency in _model)
            {
                if ((agency.CreatedBy == loggedInUserId && agency.CreatedDate.DateTime.Subtract(agency.LastModifiedDate.DateTime).Seconds == 0) ||
                    (agency.LastModifiedBy == loggedInUserId && agency.CreatedDate.DateTime.Subtract(agency.LastModifiedDate.DateTime).Seconds != 0))
                {
                    packet.AddError("Error", "You do not have permission to approve.");
                }
            }
            await Task.CompletedTask; //If you have any await in the validation, remove this line

        }

    }
}
