// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.CommonModule.VerifyAddNumberOTPCommonPlugins;

namespace ENTiger.ENCollect.CommonModule
{
    /// <summary>
    /// 
    /// </summary>
    public class VerifyAddNumberOTPSequence : FlexiBusinessRuleSequenceBase<VerifyAddNumberOTPDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public VerifyAddNumberOTPSequence()
        {
            
            this.Add<VerifyOTP>(); 
        }
    }
}
