// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Sumeru.Flex;

namespace ENTiger.ENCollect.AgencyUsersModule.ValidateAgentMobileAgencyUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateMobile : FlexiBusinessRuleBase, IFlexiBusinessRule<ValidateAgentMobileDataPacket>
    {
        public override string Id { get; set; } = "3a1486c01d3f227ab54fa236666b3f03";
        public override string FriendlyName { get; set; } = "ValidateMobile";

        protected readonly ILogger<ValidateMobile> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly ICustomUtility _customUtility;

        public ValidateMobile(ILogger<ValidateMobile> logger, IRepoFactory repoFactory, ICustomUtility customUtility)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _customUtility = customUtility;
        }

        public virtual async Task Validate(ValidateAgentMobileDataPacket packet)
        {
            _repoFactory.Init(packet.Dto);

            List<AgentMobileDto> agentlist = new List<AgentMobileDto>();
            _logger.LogInformation("ValidateMobile Started");
            if (!string.IsNullOrEmpty(packet.Dto.MobileNo))
            {
                var StaffPartyExists = await _repoFactory.GetRepo().FindAll<ApplicationUser>()
                                            .Where(p => p.PrimaryMobileNumber == packet.Dto.MobileNo &&
                                                    p.GetType() == typeof(CompanyUser))
                                            .FirstOrDefaultAsync();

                if (StaffPartyExists != null)
                {
                    packet.AddError("Error", "Staffuser already exist for same mobile no.");
                }
                else
                {
                    AgencyUserWorkflowState state = WorkflowStateFactory.GetCollectionAgencyUserWFState("disabled");
                    agentlist = await _repoFactory.GetRepo().FindAll<AgencyUser>()
                                            .IncludeAgencyUserWorkflow()
                                            .Where(p => p.PrimaryMobileNumber == packet.Dto.MobileNo &&
                                                    p.AgencyUserWorkflowState.Name == state.Name &&
                                                    p.UserId != null)
                                            .SelectTo<AgentMobileDto>()
                                            .ToListAsync();

                    _logger.LogInformation("After get agent details");

                    var departments = await _repoFactory.GetRepo().FindAll<Department>().ToListAsync();
                    var designations = await _repoFactory.GetRepo().FindAll<Designation>().ToListAsync();
                    _logger.LogInformation("After get departments and designations details");

                    if (agentlist.Count > 0)
                    {
                        foreach (var agents in agentlist)
                        {
                            agents.AgencyName = _customUtility.FullMaskValueFunc(agents.AgencyName);

                            foreach (var designation in agents.Roles)
                            {
                                var design = designations.Where(x => x.Id == designation.DesignationId).FirstOrDefault();
                                if (design != null)
                                {
                                    designation.DesignationId = design.Name;
                                }
                                var dept = departments.Where(x => x.Id == designation.DepartmentId).FirstOrDefault();
                                if (dept != null)
                                {
                                    designation.DepartmentId = dept.Name;
                                }
                            }
                        }
                    }
                    else
                    {
                        var PartyExists = await _repoFactory.GetRepo().FindAll<AgencyUser>()
                                                .IncludeAgencyUserWorkflow()
                                                .Where(p => p.PrimaryMobileNumber == packet.Dto.MobileNo &&
                                                        p.AgencyUserWorkflowState.Name != state.Name &&
                                                        p.UserId != null && p.IsDeleted == false)
                                                .FirstOrDefaultAsync();

                        _logger.LogInformation("ValidateMobile : record exist for mobile no " + PartyExists?.PrimaryEMail);
                        if (PartyExists != null)
                        {
                            packet.AddError("Error", "Mobile no already exists");
                        }
                    }
                }
            }            
            packet.OutputDto = agentlist;
        }
    }
}
