// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels;
using ENTiger.ENCollect.DomainModels.Utilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Sumeru.Flex;
using System.IO.Abstractions;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.AllocationModule.SecondaryAllocationByFilterAllocationPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateSecondaryUnAllocation : FlexiBusinessRuleBase, IFlexiBusinessRule<SecondaryUnAllocationByBatchDataPacket>
    {
        public override string Id { get; set; } = "3a139de59506a1dd7faed68e1d6d33c9";
        public override string FriendlyName { get; set; } = "ValidateSecondaryUnAllocation";
        protected readonly IFileSystem _fileSystem;
        protected readonly ILogger<ValidateSecondaryUnAllocation> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly FilePathSettings _fileSettings;
        private readonly IFileValidationUtility _fileValidationUtility;

        public ValidateSecondaryUnAllocation(
            ILogger<ValidateSecondaryUnAllocation> logger, 
            IRepoFactory repoFactory, 
            IOptions<FilePathSettings> fileSettings, 
            IFileValidationUtility fileValidationUtility,
            IFileSystem fileSystem)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _fileSettings = fileSettings.Value;
            _fileValidationUtility = fileValidationUtility;
            _fileSystem = fileSystem;
        }

        public virtual async Task Validate(SecondaryUnAllocationByBatchDataPacket packet)
        {
            _repoFactory.Init(packet.Dto);
            string _filepath = _fileSystem.Path.Combine(_fileSettings.BasePath, _fileSettings.IncomingPath);
            if (!_fileValidationUtility.CheckIfFileExists(_filepath, packet.Dto.Name))
            {
                packet.AddError("Error", "Invalid File");
            }           
            await Task.CompletedTask;
        }
    }
}
