// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using ENTiger.ENCollect.DomainModels.Settings;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.PublicModule.ImportAccountsPublicPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ValidateImportAccounts : FlexiBusinessRuleBase, IFlexiBusinessRule<ImportAccountsDataPacket>
    {
        public override string Id { get; set; } = "3a13c90acb5578ee33178a573b7d68ba";
        public override string FriendlyName { get; set; } = "ValidateImportAccounts";

        protected readonly ILogger<ValidateImportAccounts> _logger;
        protected readonly IRepoFactory _repoFactory;
        private readonly AccountImportSettings _accountImportSettings;
        public ValidateImportAccounts(ILogger<ValidateImportAccounts> logger, IRepoFactory repoFactory, IOptions<AccountImportSettings> accountImportSettings)
        {
            _logger = logger;
            _repoFactory = repoFactory;
            _accountImportSettings = accountImportSettings.Value;
        }

        public virtual async Task Validate(ImportAccountsDataPacket packet)
        {
            int count = _accountImportSettings.MaximumCount;

            if (packet.Dto.count == 0 || packet.Dto?.items == null || packet.Dto?.items.Count == 0)
            {
                packet.AddError("Error", "Invalid Request");
            }
            else
            {
                if (packet.Dto.count > count || packet.Dto?.items.Count > count)
                {
                    packet.AddError("Error", "Max records limit exceeded. Limit " + count + " per request.");
                }
            }

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
