// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;

namespace ENTiger.ENCollect.AuditTrailModule
{
    /// <summary>
    /// 
    /// </summary>
    public class AddAuditTrailSequence : FlexiBusinessRuleSequenceBase<AddAuditTrailDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public AddAuditTrailSequence()
        {
            
            
        }
    }
}
