// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.TreatmentModule.DeleteTreatmentsTreatmentPlugins;

namespace ENTiger.ENCollect.TreatmentModule
{
    /// <summary>
    /// 
    /// </summary>
    public class DeleteTreatmentsSequence : FlexiBusinessRuleSequenceBase<DeleteTreatmentsDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public DeleteTreatmentsSequence()
        {
            
            this.Add<ValidateTreatments>(); 
        }
    }
}
