// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.SegmentationModule.DisableSegmentsSegmentationPlugins;

namespace ENTiger.ENCollect.SegmentationModule
{
    /// <summary>
    /// 
    /// </summary>
    public class DisableSegmentsSequence : FlexiBusinessRuleSequenceBase<DisableSegmentsDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public DisableSegmentsSequence()
        {
            
            this.Add<ValidateSegments>(); 
        }
    }
}
