// <auto-generated>
//     This code was generated by FlexGen.
//     
//
//     Do not implement any changes in this file
//     This file will be replaced with existing plugin list when the code will be generated next time.
// </auto-generated>

using Sumeru.Flex;
using ENTiger.ENCollect.SettlementModule.RequestSettlementSettlementPlugins;

namespace ENTiger.ENCollect.SettlementModule
{
    /// <summary>
    /// 
    /// </summary>
    public class RequestSettlementSequence : FlexiBusinessRuleSequenceBase<RequestSettlementDataPacket>
    {
        /// <summary>
        /// 
        /// </summary>
        public RequestSettlementSequence()
        {            
            this.Add<OpenSettlementValidator>(); 
            this.Add<DocumentExistenceValidator>(); 
            this.Add<DeathSettlementValidator>();
            this.Add<UserBranchValidator>();
        }
    }
}
