// <auto-generated>
//     This code was generated by Sumeru FlexGen.
//     Template Version: TemplateVersion
//
//     Do not rename the file
//     TODO:
//     Implement your validations in the Validate(..) method.
// </auto-generated>

using Microsoft.Extensions.Logging;
using Sumeru.Flex;
using System.Threading.Tasks;

namespace ENTiger.ENCollect.ApplicationUsersModule.UpdateCodeOfConductApplicationUsersPlugins
{
    /// <summary>
    /// 
    /// </summary>
    public partial class IsValid : FlexiBusinessRuleBase, IFlexiBusinessRule<UpdateCodeOfConductDataPacket>
    {
        public override string Id { get; set; } = "3a180bf0507d780ecad0c3cb973407ba";
        public override string FriendlyName { get; set; } = "IsValid";

        protected readonly ILogger<IsValid> _logger;
        protected readonly IRepoFactory _repoFactory;

        public IsValid(ILogger<IsValid> logger, IRepoFactory repoFactory)
        {
            _logger = logger;
            _repoFactory = repoFactory;
        }

        public virtual async Task Validate(UpdateCodeOfConductDataPacket packet)
        {
            //Uncomment the below line if validating against a db data using your repo
            //_repoFactory.Init(packet.Dto);

            //If any validation fails, uncomment and use the below line of code to add error to the packet
            //packet.AddError("key", "ErrorMessage");

            await Task.CompletedTask; //If you have any await in the validation, remove this line
        }
    }
}
